name: Python Upper case

on: 
  push:
    paths: 
      - "py-upper/**"
      - ".github/workflows/python-uppercase.yaml"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
      - run: python -V
      - name: Download app code
      - uses: actions/checkout@v4
